- name: Deploy
  hosts: zalo_mini_app
  tasks:
    - name: Git Pull
      ansible.builtin.shell: cd zalo_mini_app && git pull origin master

    - name: NPM Install
      command: bash -lc "cd zalo_mini_app && sudo npm install"

- name: Restart
  hosts: zalo_mini_app
  serial: 1
  tasks:
    - name: Restart
      command: bash -lc "pm2 restart zalo-mini-app --update-env"
